services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      - mongodb-primary
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  mongodb-primary:
    image: mongo
    restart: always
    volumes:
      - 'mongodb_master_data:/data/db'
    ports:
      - '64000:27017'

volumes:
  mongodb_master_data:
    driver: local
